# .github/FUNDING.yml

# These are supported funding model platforms.
# By adding your usernames here, you will enable the "Sponsor" button
# on your repository, which will link to these platforms.

# Example:
# github: [ctrotech]
# patreon: your-patreon-username
# open_collective: your-open-collective-project
# ko_fi: your-ko_fi_username
# tidelift: your-tidelift-project
# community_bridge: your-community-bridge-project
# liberapay: your-liberapay-username
# issuehunt: your-issuehunt-username
#otechie: your-otechie-username
# custom: ['https://www.buymeacoffee.com/your-username', 'https://paypal.me/your-username']

# Uncomment the platforms you use and replace the placeholder text.
# For example, to enable GitHub Sponsors:
github: [ctrotech-tutor] # Replace with your actual GitHub username

